import { McpServer } from "@modelcontextprotocol/server";
import { z } from "zod";
import { ApiClient, ApiError, JsonObjectSchema, ToolResultSchema, run, success } from "./core.js";

export const SERVER_NAME = "mcp-linear-issue-manager";
export const SERVER_VERSION = "0.1.0";
type Env = Record<string, string | undefined>;

export async function graphql(api: ApiClient, query: string, variables: Record<string, unknown> = {}) {
  const payload = await api.request("POST", "/graphql", { body: { query, variables } }) as any;
  if (Array.isArray(payload?.errors) && payload.errors.length) throw new ApiError(payload.errors.map((entry: any) => entry.message).join("; "), { code: "graphql_error" });
  return payload?.data;
}

export function createServer(env: Env = {}): McpServer {
  const key = env.LINEAR_API_KEY?.trim();
  const api = new ApiClient({ baseUrl: env.LINEAR_API_BASE_URL || "https://api.linear.app", configured: Boolean(key), headers: key ? { Authorization: key } : {} });
  const server = new McpServer({ name: SERVER_NAME, version: SERVER_VERSION });
  const ro = { readOnlyHint: true, idempotentHint: true };

  server.registerTool("linear_status", { title: "Linear connection status", description: "Report non-secret Linear configuration.", inputSchema: z.object({}), outputSchema: ToolResultSchema, annotations: ro }, async () => success({ configured: api.configured, transport: "stdio-or-streamable-http" }));
  server.registerTool("get_viewer", { title: "Get Linear viewer", description: "Read the authenticated Linear user.", inputSchema: z.object({}), outputSchema: ToolResultSchema, annotations: ro }, async () => run(() => graphql(api, `query { viewer { id name email displayName } }`)));
  server.registerTool("list_teams", { title: "List teams", description: "List accessible teams and workflow states.", inputSchema: z.object({ first: z.number().int().min(1).max(100).default(50), after: z.string().optional() }), outputSchema: ToolResultSchema, annotations: ro }, async ({ first, after }) => run(() => graphql(api, `query($first:Int!,$after:String){ teams(first:$first,after:$after){ nodes { id key name states { nodes { id name type } } } pageInfo { hasNextPage endCursor } } }`, { first, after })));
  server.registerTool("list_projects", { title: "List projects", description: "List projects with status, lead, and team context.", inputSchema: z.object({ first: z.number().int().min(1).max(100).default(50), after: z.string().optional(), teamId: z.string().optional() }), outputSchema: ToolResultSchema, annotations: ro }, async ({ first, after, teamId }) => run(() => graphql(api, `query($first:Int!,$after:String,$filter:ProjectFilter){ projects(first:$first,after:$after,filter:$filter){ nodes { id name slugId state progress targetDate lead { id name } teams { nodes { id key name } } } pageInfo { hasNextPage endCursor } } }`, { first, after, filter: teamId ? { accessibleTeams: { id: { eq: teamId } } } : undefined })));
  server.registerTool("list_labels", { title: "List issue labels", description: "List workspace or team issue labels.", inputSchema: z.object({ first: z.number().int().min(1).max(100).default(100), after: z.string().optional(), teamId: z.string().optional() }), outputSchema: ToolResultSchema, annotations: ro }, async ({ first, after, teamId }) => run(() => graphql(api, `query($first:Int!,$after:String,$filter:IssueLabelFilter){ issueLabels(first:$first,after:$after,filter:$filter){ nodes { id name color description group { id name } } pageInfo { hasNextPage endCursor } } }`, { first, after, filter: teamId ? { team: { id: { eq: teamId } } } : undefined })));
  server.registerTool("search_issues", { title: "Search issues", description: "Search issues by text with optional team, project, assignee, or state filters.", inputSchema: z.object({ query: z.string().min(1), first: z.number().int().min(1).max(100).default(50), after: z.string().optional(), teamId: z.string().optional(), projectId: z.string().optional(), assigneeId: z.string().optional(), stateId: z.string().optional() }), outputSchema: ToolResultSchema, annotations: ro }, async ({ query, first, after, teamId, projectId, assigneeId, stateId }) => run(() => graphql(api, `query($term:String!,$first:Int!,$after:String,$filter:IssueFilter){ searchIssues(term:$term,first:$first,after:$after,filter:$filter){ nodes { id identifier title description priority url updatedAt team { id key } state { id name type } project { id name } assignee { id name } labels { nodes { id name } } } pageInfo { hasNextPage endCursor } } }`, { term: query, first, after, filter: { ...(teamId ? { team: { id: { eq: teamId } } } : {}), ...(projectId ? { project: { id: { eq: projectId } } } : {}), ...(assigneeId ? { assignee: { id: { eq: assigneeId } } } : {}), ...(stateId ? { state: { id: { eq: stateId } } } : {}) } })));
  server.registerTool("get_issue", { title: "Get issue", description: "Retrieve an issue by UUID or identifier.", inputSchema: z.object({ issueId: z.string().min(1) }), outputSchema: ToolResultSchema, annotations: ro }, async ({ issueId }) => run(() => graphql(api, `query($id:String!){ issue(id:$id){ id identifier title description priority estimate url createdAt updatedAt dueDate team { id key name } state { id name type } project { id name } assignee { id name email } labels { nodes { id name color } } } }`, { id: issueId })));
  server.registerTool("create_issue", { title: "Create issue", description: "Create a Linear issue.", inputSchema: z.object({ teamId: z.string().min(1), title: z.string().min(1).max(500), description: z.string().optional(), assigneeId: z.string().optional(), stateId: z.string().optional(), projectId: z.string().optional(), labelIds: z.array(z.string()).max(50).optional(), priority: z.number().int().min(0).max(4).optional(), estimate: z.number().min(0).optional(), dueDate: z.string().date().optional() }), outputSchema: ToolResultSchema, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false } }, async (input) => run(() => graphql(api, `mutation($input:IssueCreateInput!){ issueCreate(input:$input){ success issue { id identifier title url } } }`, { input })));
  server.registerTool("update_issue", { title: "Update issue", description: "Patch an issue's workflow and content fields.", inputSchema: z.object({ issueId: z.string().min(1), patch: JsonObjectSchema }), outputSchema: ToolResultSchema, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true } }, async ({ issueId, patch }) => run(() => graphql(api, `mutation($id:String!,$input:IssueUpdateInput!){ issueUpdate(id:$id,input:$input){ success issue { id identifier title updatedAt } } }`, { id: issueId, input: patch })));
  server.registerTool("archive_issue", { title: "Archive issue", description: "Archive a Linear issue.", inputSchema: z.object({ issueId: z.string().min(1) }), outputSchema: ToolResultSchema, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true } }, async ({ issueId }) => run(() => graphql(api, `mutation($id:String!){ issueArchive(id:$id){ success entity { id } } }`, { id: issueId })));

  server.registerResource("linear-issue-capabilities", "linear://server/status", { title: "Linear issue manager status", description: "Non-secret configuration and tool count.", mimeType: "application/json" }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify({ name: SERVER_NAME, version: SERVER_VERSION, configured: api.configured, tools: 10 }, null, 2) }] }));
  server.registerPrompt("linear_issue_workflow", { title: "Plan a Linear issue workflow", description: "Prepare a read-first issue and project operation.", argsSchema: z.object({ objective: z.string().min(1), teamKey: z.string().optional() }) }, ({ objective, teamKey }) => ({ messages: [{ role: "user", content: { type: "text", text: `Objective: ${objective}\n${teamKey ? `Team: ${teamKey}` : "Discover the team first."}\nSearch for duplicates and read team states, project, and labels before writes. Confirm the exact issue identifier before update or archive.` } }] }));
  return server;
}
